### ISSUE TITLE
Strange errors when making changes on the site

### ISSUE THREAD

**Issue by janette** [ABREPR/cipp#13]
commit 81eaaaa85fd3a25392fbc92ad072580a8baef863 1 parent 22ba525

When enabling debut_blog I get the following error:
    Notice: Trying to get property of non-object in debut_blog_enable() (line 28 of /var/www/cipp/webroot/sites/all/modules/debut_blog/debut_blog.install).
    Warning: array_intersect_key(): Argument #2 is not an array in debut_blog_enable() (line 28 of /var/www/cipp/webroot/sites/all/modules/debut_blog/debut_blog.install).
    Warning: array_keys() expects parameter 1 to be array, null given in debut_blog_enable() (line 28 of /var/www/cipp/webroot/sites/all/modules/debut_blog/debut_blog.install).
    Warning: Invalid argument supplied for foreach() in _features_restore() (line 888 of /var/www/cipp/webroot/profiles/dkan/modules/contrib/features/features.module).
    Warning: Invalid argument supplied for foreach() in _features_restore() (line 888 of /var/www/cipp/webroot/profiles/dkan/modules/contrib/features/features.module).
    EntityMalformedException: Missing bundle property on entity of type node. in entity_extract_ids() (line 7663 of /var/www/cipp/webroot/includes/common.inc).

when enabling the faq module it also displays the error: EntityMalformedException: Missing bundle property on entity of type node. in entity_extract_ids()

but the content type is created

**Comment by janette** [comment]
update: the blog content type is created, visible after a refresh, so not urgent, but curious issue

**Comment by janette** [comment]
Changing the group content type name from 'group' to 'government sector' generated this error:

```
Notice: Undefined index: type in rdfui_form_node_type_form_submit() (line 344 of /var/www/cipp/webroot/profiles/dkan/modules/contrib/rdfx/rdfui/rdfui.module).
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'bundle' cannot be null: INSERT INTO {rdf_mapping} (type, bundle, mapping) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2); Array ( [:db_insert_placeholder_0] => node [:db_insert_placeholder_1] => [:db_insert_placeholder_2] => a:9:{s:7:"rdftype";a:2:{i:0;s:9:"sioc:Item";i:1;s:13:"foaf:Document";}s:5:"title";a:2:{s:10:"predicates";a:1:{i:0;s:8:"dc:title";}s:4:"type";s:8:"property";}s:7:"created";a:3:{s:10:"predicates";a:2:{i:0;s:7:"dc:date";i:1;s:10:"dc:created";}s:8:"datatype";s:12:"xsd:dateTime";s:8:"callback";s:12:"date_iso8601";}s:7:"changed";a:3:{s:10:"predicates";a:1:{i:0;s:11:"dc:modified";}s:8:"datatype";s:12:"xsd:dateTime";s:8:"callback";s:12:"date_iso8601";}s:4:"body";a:1:{s:10:"predicates";a:1:{i:0;s:15:"content:encoded";}}s:3:"uid";a:2:{s:10:"predicates";a:1:{i:0;s:16:"sioc:has_creator";}s:4:"type";s:3:"rel";}s:4:"name";a:1:{s:10:"predicates";a:1:{i:0;s:9:"foaf:name";}}s:13:"comment_count";a:2:{s:10:"predicates";a:1:{i:0;s:16:"sioc:num_replies";}s:8:"datatype";s:11:"xsd:integer";}s:13:"last_activity";a:3:{s:10:"predicates";a:1:{i:0;s:23:"sioc:last_activity_date";}s:8:"datatype";s:12:"xsd:dateTime";s:8:"callback";s:12:"date_iso8601";}} ) in rdf_mapping_save() (line 239 of /var/www/cipp/webroot/modules/rdf/rdf.module).
```

but the name change is made...

**Comment by acouch** [comment]
The first is about updating features after enabling. Not sure why the error was triggered. The 'debut' feature isn't available yet for some reason. 

The second is noted here: https://drupal.org/node/1271498

There are patches if the error persists, but I think it might just be related to the initial name change: https://drupal.org/node/1271498#comment-4957274

**Comment by janette** [comment]
Notice: Undefined index: title_value in link_field_update_instance() (line 1305 of /var/www/cipp/webroot/profiles/dkan/modules/contrib/link/link.module).
