### ISSUE TITLE
Social Media urls

### ISSUE THREAD

**Issue by janette** [ABREPR/cipp#18]
we need OPR facebook url, twitter handle, linkedin url and google+ url

**Comment by acouch** [comment]
http://instagram.com/abrepuertorico
https://twitter.com/abrepuertorico
https://www.facebook.com/AbrePuertoRico

Think that is all for now.

**Comment by acouch** [comment]
Here is google+

https://plus.google.com/communities/102227212053653047640

**Comment by acouch** [comment]
Closing, we may add google+ later: #19
