### ISSUE TITLE
Videos for Content Authoring

### ISSUE THREAD

**Issue by Krista-Nuams** [ABREPR/cipp#21]
Create videos for:

1) Adding new users
2) Adding datasets
3) Explain Groups
4) Translating site elements

**Comment by Krista-Nuams** [comment]
What is the status of these?

**Comment by acouch** [comment]
Janette is updating them.

**Comment by janette** [comment]
Aaron can you post a dataset link to use for the 'how to add a dataset video'

**Comment by acouch** [comment]
Looks like the audio was a problem: https://basecamp.com/1897178/projects/2697460-open-puerto-rico/messages/13675003-how-to-translate

I don't want us to spend too much time on these. Can you make sure they have the right access to update these and reply before updating the video? Seems like if the permissions are checked we won't need to make a new one.

**Comment by janette** [comment]
Looking at the admin role they can't do much, I'm assuming the admin role should have all permissions. What role will the interns get? Do we need another role for 'Translator' or will they get the Editor role?

**Comment by acouch** [comment]
Good questions. I guess I would create a translator role and give the interns both Translator and Editor.

**Comment by acouch** [comment]
I updated the administer permissions and gave that role to Alvin.

**Comment by janette** [comment]
will Re-do videos this week:
1) Adding new users
2) Adding datasets
4) Translating site elements

updated translator role is now a stand-alone role and has access to the admin menu

**Comment by Krista-Nuams** [comment]
Can I assign Jim to "Adding new users" video while we are waiting for datasets and site elements to be fixed?
