### ISSUE TITLE
Fix or revert commit that removes page titles from dataset and resource pages

### ISSUE THREAD

**Issue by acouch** [ABREPR/cipp#25]
This commit http://drupalcode.org/project/dkan.git/commitdiff/45262b5?hp=43a42e6915e1c653271762659334622bea4e2ff1 doesn't remove the title from dataset nodes but not resources: http://cipp.nuamsdev.com/en/dataset/resource/6f74b371-e567-41a5-ac67-2792c6ee9005 in DKAN's theme and doesn't remove them from the node/add form: http://cipp.nuamsdev.com/en/node/add/dataset

Please either make the title not appear on resource nodes as well as dataset and resource forms or revert the commit and override the theme function specifically for CIPP by re-implementing it in the cipp template.php with the changes you've made.

**Comment by janette** [comment]
I've added the change to the cipp theme template.php and also tried to push the change on drupal.org, it's asking me to enter a commit message to explain the merge...

**Comment by acouch** [comment]
Can you save the change, 'git reset --hard', pull, and try again?

**Comment by janette** [comment]
the commit must have stuck – after a git reset --hard, my change was already in there

**Comment by acouch** [comment]
This was committed to DKAN. Thanks.
