### ISSUE TITLE
Add twitter block for blog

### ISSUE THREAD

**Issue by acouch** [ABREPR/cipp#39]
Use twitter_pull module. Add to blog content type and main blog page.

See:  ![](http://i.imgur.com/exdmIs9.jpg)!

**Comment by Krista-Nuams** [comment]
Push to dev

**Comment by acouch** [comment]
Please push changes to the development site. Thanks!

**Comment by ioskevich** [comment]
Standing by on decision from NUAMS if we shall keep working on CIPP tickets.
