### ISSUE TITLE
Make blog section a search page using search api

### ISSUE THREAD

**Issue by acouch** [ABREPR/cipp#40]
Result should look like this: http://www.eany.org/our-work/team-blogs

Create a new blog index and search view to do this.

**Comment by acouch** [comment]
I turned on Search API: http://cipp.nuamsdev.com/en/blog

The 'search' bar needs theming.

**Comment by mbrakken** [comment]
I'm folding this into #42 at this point. Most theming on the search is done. I just need to deal with the button and the placeholder text.
