### ISSUE TITLE
Create Open States Integration

### ISSUE THREAD

**Issue by acouch** [ABREPR/cipp#41]
We want people to be able to allow people to comment on new legislation.

OpenStates offers the ability to do this. 

1) Create a node type with the following fields:

http://sunlightlabs.github.io/openstates-api/bills.html#methods/bill-search

+

http://sunlightlabs.github.io/openstates-api/bills.html#methods/bill-detail
http://sunlightlabs.github.io/openstates-api/bills.html#bill-fields

We don't need all of the fields for the bill detail. Start with type, chamber, date fields, sponsors.

2) Create Feeds Importer using feeds_json to import recent bills. Periodic import should be set to 3 days.

3) Add comments and voting + fivestar. See dataset voting for example.

4) Create list of recent bills + rating

**Comment by Krista-Nuams** [comment]
Did you post to stack exchange?

**Comment by acouch** [comment]
Yeah.

**Comment by acouch** [comment]
This should be done with migrate module. Can stamp out version of this this eve.
