### ISSUE TITLE
dkan_dataset_voting files replicated outside of module folder

### ISSUE THREAD

**Issue by mbrakken** [ABREPR/cipp#56]
There are dkan_dataset_voting files nested within profiles/dkan/modules/dkan/dkan_dataset/modules as well as in profiles/dkan/modules/dkan/dkan_dataset/modules/dkan_dataset_voting.

I assume those outside the module can just be deleted.

**Comment by mbrakken** [comment]
There's also a version of dkan_dataset.forms.inc within profiles/dkan/modules/dkan and one within profiles/dkan/modules/dkan/dkan_dataset. The first one has a more recent commit history, but I haven't compared it with the other one.

**Comment by acouch** [comment]
This has been fixed.
