### ISSUE TITLE
Add data sections (municapal etc, adapt groups)

### ISSUE THREAD

**Issue by Krista-Nuams** [ABREPR/cipp#6]
See: https://asset1.basecamp.com/1897178/projects/2697460-open-puerto-rico/attachments/38379669/c5359097c88816729a62757d2b7c06540000/original/Open%20Puerto%20Rico%20Sitemap%201.0.pdf

and wireframes

**Comment by janette** [comment]
I've added the groups, so those all have pages but not the data pages

**Comment by acouch** [comment]
Great
