### ISSUE TITLE
Mobile: Nav

### ISSUE THREAD

**Issue by federicca** [ABREPR/cipp#66]
Mobile Main Nav:

Width not adjusted and the whole site breaks plus Menu doesn't appear fully

![photo 1](https://f.cloud.github.com/assets/1379537/1283842/cf50e334-2f8b-11e3-9a72-a9dba5aef2fa.PNG)

![photo 2](https://f.cloud.github.com/assets/1379537/1283860/f7719f84-2f8b-11e3-85cb-acf7a9907d6f.PNG)

**Comment by acouch** [comment]
This has been addressed.
