### ISSUE TITLE
Add get involved / about pages

### ISSUE THREAD

**Issue by Krista-Nuams** [ABREPR/cipp#7]
Create blank "About", "Board", "Supporters and Partners", "Get Involved", "Developer", "Press" "Terms and Conditions" , "Privacy Policy" pages per site map: https://asset1.basecamp.com/1897178/projects/2697460-open-puerto-rico/attachments/38379669/c5359097c88816729a62757d2b7c06540000/original/Open%20Puerto%20Rico%20Sitemap%201.0.pdf

**Comment by janette** [comment]
need to set up a dropdown menu module, will install superfish and theme it

**Comment by janette** [comment]
I did not see where the links for Terms, Privacy, Contact us were supposed to be set up, they are not in the mockup, any ideas?

**Comment by acouch** [comment]
Krista, can you ask them about the questions above?

**Comment by janette** [comment]
I can put them in the footer, sound good?

**Comment by Krista-Nuams** [comment]
OK. The only one I'm not sure about is the Contact Us as it relates to the main Nav item About Us.  I guess that would also link to a contact us page?
Should I ask that?

**Comment by janette** [comment]
I can put the contact us link under the About link in the main menu, and then terms and privacy in the footer. When a user is registering for an account is there supposed to be a required check box for terms?

**Comment by acouch** [comment]
I'm just going to assume 'no' on the checkbox.

**Comment by acouch** [comment]
Is this finished?

**Comment by janette** [comment]
done
