### ISSUE TITLE
Multilingual

### ISSUE THREAD

**Issue by Krista-Nuams** [ABREPR/cipp#8]
Default language should be Spanish.

Download and install i18n and enable. Add English translation for main menu.

**Comment by janette** [comment]
what content will have an English equivalent? all content types, only non-dataset content, vise-versa?

**Comment by Krista-Nuams** [comment]
Hmm I think some datasets will be only English or only Spanish but otherwise it should all be bilingual. We should probably confirm this with client. I'll make a basecamp post.

**Comment by janette** [comment]
i18n is installed and ready to go

**Comment by acouch** [comment]
Closing as Janette has added the basic multilingual elements. This will get broken down into smaller tickets.
